### ISSUE TITLE
Package not visible in Winter '21 Orgs - any flows using it fail and cannot be opened

### ISSUE THREAD

**Issue by AlexKasper** [ericrsmith35/DatatableV2#47]
Flows using this component in my (just updated) Winter '21 sandbox or production orgs cannot be opened, deployed or even downloaded using workbench. It's as if the flow XML files no longer exist.

Further, the DatatableV2 package no longer shows as installed. Attempting to re-install seems to be successful, however the package is still not listed in the org and when making a new flow, DatatableV2 is not available as a component to use.

It was working perfectly last night and this morning, after the Winter '21 upgrade, all flows using it display the following error:

**Something went wrong**
_Hmm, that didn't work. Reload the flow list page and open the flow from there. For help, contact Salesforce Customer Support. Error ID: 1685530200_

**Comment by ericrsmith35** [comment]
Starting in Winter '21, all users accessing @AuraEnabled Apex methods must have specific authorization to access the class in their profile or a permission set.  In this case, you must assign access for SObjectController2.  

https://releasenotes.docs.salesforce.com/en-us/winter21/release-notes/rn_lc_restrict_apex_authenticated_users.htm

Using the Deploy to Salesforce button does not update any listings in "Installed Packages" because the components are installed individually rather than as a package.

**Comment by AlexKasper** [comment]
Wow, thanks much for the link and shame on me for not cluing in on this from the update release notes. That makes sense. Thanks for a great tool and greetings from Berlin!

**Comment by ericrsmith35** [comment]
Glad that this is working again for you and greetings back to you from
Maine.
