### ISSUE TITLE
there is a way to add permission to edit Time field?

### ISSUE THREAD

**Issue by BenKeshet** [ericrsmith35/DatatableV2#66]
![Screen Shot 2020-12-21 at 14 16 51](https://user-images.githubusercontent.com/76433669/102776357-47e14380-4397-11eb-908b-75871015f20c.png)

**Comment by ericrsmith35** [comment]
I have not been able to come up with a way to do this yet.  Salesforce doesn't allow editing of Time fields in their Listviews either.  In order to display the time fields in the datatable with the correct timezone, I end up converting the values to datetime values before formatting them for display in the datatable.  I have not been able to find a way to convert the edited values back to a time value in order to update the records.
